### ISSUE TITLE
Blank Window in Windows.

### ISSUE THREAD

**Issue by mysticatea** [rhysd/Trendy#3]
I downloaded and unzipped `trendy-v0.1.1-win32-x64.zip`.
Then I ran `Trendy.exe`.

![image](https://cloud.githubusercontent.com/assets/1937871/10066656/07391900-62d0-11e5-93b9-41934b1cde41.png)

Also, I clicked the "Settings" button in the first window, then it just opens `C:\...\AppData\Roaming\Trendy\config.json` with my default editor.

---

Windows 7 64bit

**Comment by rhysd** [comment]
hmm...  Sorry for inconvenience.

> blank window

I'll check it in Windows7 because I don't have Windows environment and cannot test very well...
I think languages picker window doesn't work in Windows.

![](https://raw.githubusercontent.com/rhysd/Trendy/master/resource/image/lang-picker.png)

For now,  you can simply close the blank window and add languages to `config.json` as workaround.

**Comment by mysticatea** [comment]
Don't worry. Now, I can use Trendy, thanks for that workaround.
Thank you for the great tool. :)

**Comment by rhysd** [comment]
This issue should be fixed in version 0.1.2.
